name: PR - CI
on: 
  pull_request:
    branches: [ main ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: LS
      run: |
        pwd; ls -hl .; ls -hl /home/runner/work/OrchardCore.Commerce/OrchardCore.Commerce/tools;ls -hl /home/runner/work/OrchardCore.Commerce/OrchardCore.Commerce/tools/Lombiq.Analyzers
    - name: Static Code Analysis
      run: |
        dotnet build OrchardCore.Commerce.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./OrchardCore.Commerce.Tests/OrchardCore.Commerce.Tests.csproj

  
